version: "3.3"

services:
  #mongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    networks:
      - nginx_default
    ports:
      - 27019:27017
    volumes:
      - mongo_db:/data/db

  #nodejs services
  investigo_webserver:
    build: .
    environment:
      PORT: 5000
      DATABASE: mongodb://mongo_db:27017/
      DB_NAME: investico
    depends_on:
      - mongo_db
    networks:
      - nginx_default

volumes:
  mongo_db: {}

networks:
  nginx_default:
    external: true
